/**
 * Takes Astro's autogenerated URL and corrects it to the format we expect.
 *
 * Needed because our entry files live outside the `pages` directory,
 * and so Astro's autogenerated URL will be incorrect.
 */
export function getCorrectedEntryUrl(
  astroUrl: string | undefined,
  filePath: string
): string {
  if (!astroUrl) return "";

  return [
    "", // Force a  `/` to be prepended to the final joined string.
    ...(astroUrl.split("/") || []).filter(
      (segment) =>
        segment !== "src" && segment !== "entries" && !segment.match(/\.mdx?$/)
    ),
    getNormalizedEntryFileName(getEntryFileNameFromFilePath(filePath, true)),
  ].join("/");
}

export function getEntryFileNameFromFilePath(
  filePath: string,
  removeExtension = false
): string {
  const filePathSegments = filePath.split("/");
  const fileName = filePathSegments[filePathSegments.length - 1] || "";

  return removeExtension ? fileName.replace(/\.mdx?$/, "") : fileName;
}

export function getNormalizedEntryFileName(fileName: string): string {
  return fileName.replace(/--\d+-/, "--");
}

export function getParentEntryFileName(fileName: string): string {
  return fileName.replace(/--.*$/, "");
}
